services:
  auth-database:
    ports:
      - "55100:5432"
    image: postgres:${POSTGRES_DATABASE_VERSION}
    environment:
      - POSTGRES_USER=${POSTGRES_DATABASE_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DATABASE_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE_NAME}
  redis-database:
    ports:
      - "63791:6379"
    image: redis:${REDIS_DATABASE_VERSION}