services:
  authentication-database:
    ports:
      - "55000:5432"
    image: postgres:${DATABASE_VERSION}
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
  redis-storage:
    ports:
      - "63791:6379"
    image: redis:7.4